version: '3.8'

services:
  spring-app:
    container_name: Fring-server
    image: ${DOCKER_USERNAME}/fring-server:latest
    ports: []
    expose:
      - "8080"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_ACCESSKEY=${S3_ACCESSKEY}
      - S3_SECRETKEY=${S3_SECRETKEY}
    restart: always
    pull_policy: always

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  redis:
    container_name: Fring-redis
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      []
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge